
#ifndef __CUST_GPIO_USAGE_H__
#define __CUST_GPIO_USAGE_H__


#define GPIO_SPEAKER_EN_PIN         GPIO17
#define GPIO_SPEAKER_EN_PIN_M_GPIO   GPIO_MODE_00
#define GPIO_SPEAKER_EN_PIN_M_LPD   GPIO_MODE_01
#define GPIO_SPEAKER_EN_PIN_M_DPI_B   GPIO_MODE_04
#define GPIO_SPEAKER_EN_PIN_M_DBG_OUT   GPIO_MODE_05
#define GPIO_SPEAKER_EN_PIN_M_DBG_OUT   GPIO_MODE_06
#define GPIO_SPEAKER_EN_PIN_M_CONN_MCU_TCK   GPIO_MODE_07

#define GPIO_SDHC_EINT_PIN         GPIO24
#define GPIO_SDHC_EINT_PIN_M_GPIO   GPIO_MODE_00
#define GPIO_SDHC_EINT_PIN_M_LPD   GPIO_MODE_01
#define GPIO_SDHC_EINT_PIN_M_MC1_INS   GPIO_MODE_02
#define GPIO_SDHC_EINT_PIN_M_DPI_G   GPIO_MODE_04
#define GPIO_SDHC_EINT_PIN_M_DBG_OUT   GPIO_MODE_06
#define GPIO_SDHC_EINT_PIN_M_CONN_GPIO   GPIO_MODE_07

#define GPIO_SIM2_HOT_PLUG         GPIO28
#define GPIO_SIM2_HOT_PLUG_M_GPIO   GPIO_MODE_00
#define GPIO_SIM2_HOT_PLUG_M_EINT   GPIO_MODE_02
#define GPIO_SIM2_HOT_PLUG_M_MD_EINT   GPIO_MODE_05

#define GPIO_SIM1_HOT_PLUG         GPIO29
#define GPIO_SIM1_HOT_PLUG_M_GPIO   GPIO_MODE_00
#define GPIO_SIM1_HOT_PLUG_M_EINT   GPIO_MODE_02
#define GPIO_SIM1_HOT_PLUG_M_MD_EINT   GPIO_MODE_05

#define GPIO_MATV_N_RST         GPIO56
#define GPIO_MATV_N_RST_M_GPIO   GPIO_MODE_00
#define GPIO_MATV_N_RST_M_EINT   GPIO_MODE_04
#define GPIO_MATV_N_RST_M_SD_DAT   GPIO_MODE_01
#define GPIO_MATV_N_RST_M_LPA   GPIO_MODE_02
#define GPIO_MATV_N_RST_M_SFCS   GPIO_MODE_03
#define GPIO_MATV_N_RST_M_DPI_DE   GPIO_MODE_05

#define GPIO_CTP_RST_PIN         GPIO57
#define GPIO_CTP_RST_PIN_M_GPIO   GPIO_MODE_00
#define GPIO_CTP_RST_PIN_M_EINT   GPIO_MODE_04
#define GPIO_CTP_RST_PIN_M_SD_DAT   GPIO_MODE_01

#define GPIO_DISP_LRSTB_PIN         GPIO59
#define GPIO_DISP_LRSTB_PIN_M_GPIO   GPIO_MODE_00
#define GPIO_DISP_LRSTB_PIN_M_SD_CK   GPIO_MODE_01
#define GPIO_DISP_LRSTB_PIN_M_LRSTB   GPIO_MODE_02
#define GPIO_DISP_LRSTB_PIN_M_SFOUT   GPIO_MODE_03

#define GPIO_MSE_EINT_PIN         GPIO87
#define GPIO_MSE_EINT_PIN_M_GPIO   GPIO_MODE_00
#define GPIO_MSE_EINT_PIN_M_EINT   GPIO_MODE_01
#define GPIO_MSE_EINT_PIN_M_KCOL   GPIO_MODE_03
#define GPIO_MSE_EINT_PIN_M_SFCS   GPIO_MODE_02
#define GPIO_MSE_EINT_PIN_M_TDD_TXD   GPIO_MODE_04
#define GPIO_MSE_EINT_PIN_M_JTCK   GPIO_MODE_05
#define GPIO_MSE_EINT_PIN_M_DBG_OUT   GPIO_MODE_06
#define GPIO_MSE_EINT_PIN_M_CONN_GPIO   GPIO_MODE_07

#define GPIO_CAMERA_CMPDN_PIN         GPIO88
#define GPIO_CAMERA_CMPDN_PIN_M_GPIO   GPIO_MODE_00
#define GPIO_CAMERA_CMPDN_PIN_M_EINT   GPIO_MODE_01
#define GPIO_CAMERA_CMPDN_PIN_M_KCOL   GPIO_MODE_03
#define GPIO_CAMERA_CMPDN_PIN_M_MC1_INS   GPIO_MODE_02
#define GPIO_CAMERA_CMPDN_PIN_M_JTMS   GPIO_MODE_05
#define GPIO_CAMERA_CMPDN_PIN_M_DBG_OUT   GPIO_MODE_06
#define GPIO_CAMERA_CMPDN_PIN_M_CONN_GPIO   GPIO_MODE_07

#define GPIO_CAMERA_CMRST1_PIN         GPIO89
#define GPIO_CAMERA_CMRST1_PIN_M_GPIO   GPIO_MODE_00
#define GPIO_CAMERA_CMRST1_PIN_M_EINT   GPIO_MODE_01
#define GPIO_CAMERA_CMRST1_PIN_M_KROW   GPIO_MODE_03
#define GPIO_CAMERA_CMRST1_PIN_M_SCL   GPIO_MODE_02
#define GPIO_CAMERA_CMRST1_PIN_M_SIM1_SRST   GPIO_MODE_04
#define GPIO_CAMERA_CMRST1_PIN_M_JTDI   GPIO_MODE_05
#define GPIO_CAMERA_CMRST1_PIN_M_DBG_OUT   GPIO_MODE_06
#define GPIO_CAMERA_CMRST1_PIN_M_CONN_GPIO   GPIO_MODE_07

#define GPIO_CAMERA_CMPDN1_PIN         GPIO90
#define GPIO_CAMERA_CMPDN1_PIN_M_GPIO   GPIO_MODE_00
#define GPIO_CAMERA_CMPDN1_PIN_M_EINT   GPIO_MODE_01
#define GPIO_CAMERA_CMPDN1_PIN_M_KCOL   GPIO_MODE_03
#define GPIO_CAMERA_CMPDN1_PIN_M_SDA   GPIO_MODE_02
#define GPIO_CAMERA_CMPDN1_PIN_M_SIM2_SRST   GPIO_MODE_04
#define GPIO_CAMERA_CMPDN1_PIN_M_JTDO   GPIO_MODE_05
#define GPIO_CAMERA_CMPDN1_PIN_M_DBG_OUT   GPIO_MODE_06
#define GPIO_CAMERA_CMPDN1_PIN_M_CONN_GPIO   GPIO_MODE_07

#define GPIO_MATV_I2S_WS_PIN         GPIO97
#define GPIO_MATV_I2S_WS_PIN_M_GPIO   GPIO_MODE_00
#define GPIO_MATV_I2S_WS_PIN_M_EINT   GPIO_MODE_04
#define GPIO_MATV_I2S_WS_PIN_M_KROW   GPIO_MODE_03
#define GPIO_MATV_I2S_WS_PIN_M_SPI_CS   GPIO_MODE_01
#define GPIO_MATV_I2S_WS_PIN_M_I2S_IN_WS   GPIO_MODE_02
#define GPIO_MATV_I2S_WS_PIN_M_DPI_B   GPIO_MODE_05
#define GPIO_MATV_I2S_WS_PIN_M_DBG_OUT   GPIO_MODE_06
#define GPIO_MATV_I2S_WS_PIN_M_MD_CDMA_GPS_SYNC   GPIO_MODE_07

#define GPIO_MATV_I2S_CK_PIN         GPIO98
#define GPIO_MATV_I2S_CK_PIN_M_GPIO   GPIO_MODE_00
#define GPIO_MATV_I2S_CK_PIN_M_EINT   GPIO_MODE_04
#define GPIO_MATV_I2S_CK_PIN_M_KROW   GPIO_MODE_03
#define GPIO_MATV_I2S_CK_PIN_M_SPI_SCK   GPIO_MODE_01
#define GPIO_MATV_I2S_CK_PIN_M_I2S_IN_CK   GPIO_MODE_02
#define GPIO_MATV_I2S_CK_PIN_M_DPI_B   GPIO_MODE_05
#define GPIO_MATV_I2S_CK_PIN_M_DBG_OUT   GPIO_MODE_06
#define GPIO_MATV_I2S_CK_PIN_M_MD_EXT_FRAME_SYNC   GPIO_MODE_07

#define GPIO_MATV_I2S_DAT_PIN         GPIO99
#define GPIO_MATV_I2S_DAT_PIN_M_GPIO   GPIO_MODE_00
#define GPIO_MATV_I2S_DAT_PIN_M_EINT   GPIO_MODE_04
#define GPIO_MATV_I2S_DAT_PIN_M_KROW   GPIO_MODE_03
#define GPIO_MATV_I2S_DAT_PIN_M_SPI_MOSI   GPIO_MODE_01
#define GPIO_MATV_I2S_DAT_PIN_M_I2S_IN_DAT   GPIO_MODE_02
#define GPIO_MATV_I2S_DAT_PIN_M_DPI_G   GPIO_MODE_05
#define GPIO_MATV_I2S_DAT_PIN_M_DBG_OUT   GPIO_MODE_06

#define GPIO_UART_URXD2_PIN         GPIO101
#define GPIO_UART_URXD2_PIN_M_GPIO   GPIO_MODE_00
#define GPIO_UART_URXD2_PIN_M_EINT   GPIO_MODE_02
#define GPIO_UART_URXD2_PIN_M_URXD   GPIO_MODE_01
#define GPIO_UART_URXD2_PIN_M_SCL   GPIO_MODE_03
#define GPIO_UART_URXD2_PIN_M_JTCK   GPIO_MODE_04
#define GPIO_UART_URXD2_PIN_M_DPI_R   GPIO_MODE_05

#define GPIO_UART_UTXD2_PIN         GPIO102
#define GPIO_UART_UTXD2_PIN_M_GPIO   GPIO_MODE_00
#define GPIO_UART_UTXD2_PIN_M_PWM   GPIO_MODE_02
#define GPIO_UART_UTXD2_PIN_M_UTXD   GPIO_MODE_01
#define GPIO_UART_UTXD2_PIN_M_SDA   GPIO_MODE_03
#define GPIO_UART_UTXD2_PIN_M_JTMS   GPIO_MODE_04
#define GPIO_UART_UTXD2_PIN_M_DPI_R   GPIO_MODE_05

#define GPIO_UART_URXD1_PIN         GPIO103
#define GPIO_UART_URXD1_PIN_M_GPIO   GPIO_MODE_00
#define GPIO_UART_URXD1_PIN_M_URXD   GPIO_MODE_01
#define GPIO_UART_URXD1_PIN_M_MD_URXD   GPIO_MODE_05
#define GPIO_UART_URXD1_PIN_M_CONN_MCU_AICE_TCKC   GPIO_MODE_07

#define GPIO_UART_UTXD1_PIN         GPIO104
#define GPIO_UART_UTXD1_PIN_M_GPIO   GPIO_MODE_00
#define GPIO_UART_UTXD1_PIN_M_UTXD   GPIO_MODE_01
#define GPIO_UART_UTXD1_PIN_M_MD_UTXD   GPIO_MODE_05
#define GPIO_UART_UTXD1_PIN_M_CONN_MCU_AICE_TMSC   GPIO_MODE_07

#define GPIO_KPD_KCOL0_PIN         GPIO107
#define GPIO_KPD_KCOL0_PIN_M_GPIO   GPIO_MODE_00
#define GPIO_KPD_KCOL0_PIN_M_KCOL   GPIO_MODE_01

#define GPIO_KPD_KCOL1_PIN         GPIO108
#define GPIO_KPD_KCOL1_PIN_M_GPIO   GPIO_MODE_00
#define GPIO_KPD_KCOL1_PIN_M_EINT   GPIO_MODE_02
#define GPIO_KPD_KCOL1_PIN_M_KCOL   GPIO_MODE_01
#define GPIO_KPD_KCOL1_PIN_M_PWM   GPIO_MODE_03

#define GPIO_KPD_KROW0_PIN         GPIO110
#define GPIO_KPD_KROW0_PIN_M_GPIO   GPIO_MODE_00
#define GPIO_KPD_KROW0_PIN_M_KROW   GPIO_MODE_01

#define GPIO_I2C1_SCA_PIN         GPIO113
#define GPIO_I2C1_SCA_PIN_M_GPIO   GPIO_MODE_00
#define GPIO_I2C1_SCA_PIN_M_SCL   GPIO_MODE_01

#define GPIO_I2C1_SDA_PIN         GPIO114
#define GPIO_I2C1_SDA_PIN_M_GPIO   GPIO_MODE_00
#define GPIO_I2C1_SDA_PIN_M_SDA   GPIO_MODE_01

#define GPIO_CTP_EINT_PIN         GPIO129
#define GPIO_CTP_EINT_PIN_M_GPIO   GPIO_MODE_00
#define GPIO_CTP_EINT_PIN_M_CLK   GPIO_MODE_05
#define GPIO_CTP_EINT_PIN_M_EINT   GPIO_MODE_02
#define GPIO_CTP_EINT_PIN_M_PWM   GPIO_MODE_01
#define GPIO_CTP_EINT_PIN_CLK     CLK_OUT1
#define GPIO_CTP_EINT_PIN_FREQ    GPIO_CLKSRC_NONE

#define GPIO_MATV_PWR_ENABLE         GPIO134
#define GPIO_MATV_PWR_ENABLE_M_GPIO   GPIO_MODE_00
#define GPIO_MATV_PWR_ENABLE_M_PWM   GPIO_MODE_04
#define GPIO_MATV_PWR_ENABLE_M_BPI_BUS   GPIO_MODE_01
#define GPIO_MATV_PWR_ENABLE_M_ANT_SEL   GPIO_MODE_02
#define GPIO_MATV_PWR_ENABLE_M_I2S_OUT_WS   GPIO_MODE_05
#define GPIO_MATV_PWR_ENABLE_M_DBG_OUT   GPIO_MODE_06
#define GPIO_MATV_PWR_ENABLE_M_CONN_GPIO   GPIO_MODE_07

#define GPIO_ACCDET_EINT_PIN         GPIO135
#define GPIO_ACCDET_EINT_PIN_M_GPIO   GPIO_MODE_00
#define GPIO_ACCDET_EINT_PIN_M_EINT   GPIO_MODE_04
#define GPIO_ACCDET_EINT_PIN_M_BPI_BUS   GPIO_MODE_01
#define GPIO_ACCDET_EINT_PIN_M_ANT_SEL   GPIO_MODE_02
#define GPIO_ACCDET_EINT_PIN_M_I2S_OUT_CK   GPIO_MODE_05
#define GPIO_ACCDET_EINT_PIN_M_DBG_OUT   GPIO_MODE_06
#define GPIO_ACCDET_EINT_PIN_M_CONN_GPIO   GPIO_MODE_07

#define GPIO_GPS_LNA_PIN         GPIO136
#define GPIO_GPS_LNA_PIN_M_GPIO   GPIO_MODE_00
#define GPIO_GPS_LNA_PIN_M_EINT   GPIO_MODE_04
#define GPIO_GPS_LNA_PIN_M_BPI_BUS   GPIO_MODE_01
#define GPIO_GPS_LNA_PIN_M_ANT_SEL   GPIO_MODE_02
#define GPIO_GPS_LNA_PIN_M_SFCS2_MX   GPIO_MODE_03
#define GPIO_GPS_LNA_PIN_M_I2S_OUT_DAT   GPIO_MODE_05
#define GPIO_GPS_LNA_PIN_M_DBG_OUT   GPIO_MODE_06
#define GPIO_GPS_LNA_PIN_M_CONN_GPIO   GPIO_MODE_07

#define GPIO_ALS_EINT_PIN         GPIO143
#define GPIO_ALS_EINT_PIN_M_GPIO   GPIO_MODE_00
#define GPIO_ALS_EINT_PIN_M_EINT   GPIO_MODE_03
#define GPIO_ALS_EINT_PIN_M_KROW   GPIO_MODE_05
#define GPIO_ALS_EINT_PIN_M_PWM   GPIO_MODE_02

#define GPIO_GSE_1_EINT_PIN         GPIO144
#define GPIO_GSE_1_EINT_PIN_M_GPIO   GPIO_MODE_00
#define GPIO_GSE_1_EINT_PIN_M_EINT   GPIO_MODE_03
#define GPIO_GSE_1_EINT_PIN_M_KROW   GPIO_MODE_05
#define GPIO_GSE_1_EINT_PIN_M_PWM   GPIO_MODE_02
#define GPIO_GSE_1_EINT_PIN_M_BPI_BUS   GPIO_MODE_01
#define GPIO_GSE_1_EINT_PIN_M_I2S_IN_DAT   GPIO_MODE_04
#define GPIO_GSE_1_EINT_PIN_M_DBG_OUT   GPIO_MODE_06
#define GPIO_GSE_1_EINT_PIN_M_CONN_GPIO   GPIO_MODE_07

#define GPIO_ANT_SW_PIN         GPIO145
#define GPIO_ANT_SW_PIN_M_GPIO   GPIO_MODE_00
#define GPIO_ANT_SW_PIN_M_EINT   GPIO_MODE_03
#define GPIO_ANT_SW_PIN_M_KROW   GPIO_MODE_05
#define GPIO_ANT_SW_PIN_M_PWM   GPIO_MODE_02
#define GPIO_ANT_SW_PIN_M_BPI_BUS   GPIO_MODE_01
#define GPIO_ANT_SW_PIN_M_LSDI   GPIO_MODE_04
#define GPIO_ANT_SW_PIN_M_DBG_OUT   GPIO_MODE_06
#define GPIO_ANT_SW_PIN_M_CONN_GPIO   GPIO_MODE_07


/*Output for default variable names*/
/*@XXX_XX_PIN in gpio.cmp          */



#endif /* __CUST_GPIO_USAGE_H__ */


